language: python
python:
    - "2.7"
sudo: required
install:
    - pip install pyactor
    - pip install pycodestyle
    - pip install coveralls
    - pip install codecov
script:
    - find ./source -name \*.py
after_success:
    - coveralls
notifications:
    email: false