language: python
python:
    - "2.7"
sudo: required
install:
    - pip install pyactor
    - pip install pycodestyle
    - pip install coveralls
    - pip install codecov
script:
    - find ./src -name \*.py -exec pycodestyle {} +
    - nosetests --with-coverage --cover-erase --cover-package=src -v
after_success:
    - coveralls
notifications:
    email: false