language: python
python:
    - "2.7"
sudo: required
install:
    - pip install pyactor
    - pip install pycodestyle
    - pip install coveralls
    - pip install codecov
    - pip install matplotlib
script:
    - find ./src -type f \( -iname "*.py" ! -iname "main.py" "host.py" \)
    - nosetests --with-coverage --cover-erase --cover-package=src -v
after_success:
    - coveralls
notifications:
    email: false